language: node_js
cache:
  directories:
    - ~/.npm
env:
  - REPO=wesleycharlesblake/nodejs-web-socket
node_js:
  - '10'
script:
  - echo "run tests"
before_deploy:
  - bash ./scripts/docker-build.sh
deploy:
  - provider: script
    script: 
      - bash ./scripts/docker-push.sh
    on:
      all_branches: true
after_deploy:
  - npm run travis-deploy-once "npm run semantic-release"
