language: node_js
cache:
  directories:
    - ~/.npm
env:
  - REPO=wesleycharlesblake/nodejs-web-socket
node_js:
  - '10'
script:
  - echo "run tests"

jobs:
  include:
    - stage: release
      language: node_js
      node_js: '10'
      services:
        - docker
      script:
        - docker build -t wesleycharlesblake/nodejs-web-socket .
        - npm run semantic-release
 
stages:
  - name: release
    if: branch = master AND type = push AND fork = false
 
branches:
  except:
    - /^v\d+\.\d+\.\d+$/